messages:
  toggle-off: '&aСообщения подключения были скрыты.'
  toggle-on: '&aСообщения подключения снова видны.'
  join: '&7%player% &fприсоединился к серверу'
  quit: '&7%player% &fотключился от сервера'
  console-error: '&cЭта команда может быть использована только игроком в игре.'
  admin-help: |-
    &eConnectionMsgs команды:
    &b/connectionmsgs reload &7- перезагрузить конфигурацию
    &b/connectionmsgs version &7- показать версию плагина
  config-reloaded: '&aКонфигурация ConnectionMsgs успешно перезагружена!'
  version-info: |-
    &eConnectionMsgs версия: &b%version%
    &eАвтор: &b%author%
    &eРазработан для проекта /new places/ на базе 2b2tJoinLeave с Oldfag.org
  unknown-subcommand: '&cНеизвестная подкоманда. Используйте /connectionmsgs без параметров для справки.'
  console-only: '&cЭта команда доступна только в консоли сервера.'
