messages:
  toggle-off: '&aСообщения подключения были скрыты.'
  toggle-on: '&aСообщения подключения снова видны.'
  join: '&7%player% &fприсоединился к серверу'
  quit: '&7%player% &fотключился от сервера'
  console-error: '&cЭта команда может быть использована только игроком в игре.'
